settings:
  port: 'COM3'
  ee_site_name: 'joint6'
  floor_limit: 0.07
  gripper_open_pwm: 2979
  gripper_close_pwm: 1901
  joint_speed: 6

joint_config:
  offsets: [0.00, 0.25, -1.57, 0.00, 2.29, 0.00]
  motor_dir: [1, 1, 1, 1, 1, 1]
  limits:
    - [900, 3000]   # J1: 몸통
    - [800, 2000]   # J2: 허리
    - [1000, 3500]  # J3: 팔꿈치
    - [700, 3500]   # J4: 손목 끄덕
    - [0, 4095]     # J5: 손목 회전
    - [1500, 3500]  # J6: 그리퍼

pincer_search:
  sweep_speed: 6
  collision_thresh: 60
  initial_pose: [2048, 1900, 1050, 1000, 3300, 2000]
  right_extended_pose: [990, 1900, 3150, 1850, 3300, 2000]  # 우측 한계에서의 확장 자세
  left_extended_pose: [3000, 1900, 3150, 1850, 3300, 2000]  # 좌측 한계에서의 확장 자세
  approach_target_offset: [0, 1080, 3150, 1850, 3300, 2000]  # 거리 측정 시 목표 자세 (J0는 중앙값 유지)

z_search:
  descend_speed: 10
  collision_thresh: 60
  lowest_j2_pwm: 850
  lift_j2_pwm: 1900