settings:
  port: 'COM3'
  ee_site_name: 'joint6'
  floor_limit: 0.07
  gripper_open_pwm: 2979
  gripper_close_pwm: 1901
  joint_speed: 6

joint_config:
  offsets: [0.00, 0.25, -1.57, 0.00, 2.29, 0.00]
  motor_dir: [1, 1, 1, 1, 1, 1]
  limits:
    - [900, 3000]   # J1: 몸통
    - [800, 2000]   # J2: 허리
    - [1000, 3500]  # J3: 팔꿈치
    - [700, 3500]   # J4: 손목 끄덕
    - [0, 4095]     # J5: 손목 회전
    - [1500, 3500]  # J6: 그리퍼

pincer_search:
  sweep_speed: 6
  collision_thresh: 60
  right_limit_j0: 993
  left_limit_j0: 3000
  initial_pose: [2048, 1623, 1171, 1289, 3000, 2130]

z_search:
  descend_speed: 2
  collision_thresh: 60
  lowest_j2_pwm: 850
  lift_j2_pwm: 1900